# Generated by Django 6.1.2 on 2026-10-08 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_magasin', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'magasin',
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marque',
            },
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_commande', models.CharField(max_length=50, unique=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(max_length=30)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('cree_par', models.CharField(max_length=100)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.fournisseur')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.magasin')),
            ],
            options={
                'db_table': 'commande_fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_livraison', models.CharField(max_length=50, unique=True)),
                ('date_livraison', models.DateTimeField()),
                ('statut', models.CharField(max_length=30)),
                ('bon_livraison', models.CharField(blank=True, max_length=100, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('cree_par', models.CharField(max_length=100)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.commandefournisseur')),
            ],
            options={
                'db_table': 'livraison',
            },
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_produit', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('code_barres', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unite_mesure', models.CharField(max_length=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.categorie')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.marque')),
            ],
            options={
                'db_table': 'produits',
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantite_commandee', models.DecimalField(decimal_places=3, max_digits=12)),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.commandefournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produits')),
            ],
            options={
                'db_table': 'ligne_commande_fournisseur',
                'unique_together': {('commande', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='LigneLivraison',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantite_recue', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantite_acceptee', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantite_endommagee', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantite_manquante', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ligne_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.lignecommandefournisseur')),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.livraison')),
            ],
            options={
                'db_table': 'ligne_livraison',
                'unique_together': {('livraison', 'ligne_commande')},
            },
        ),
    ]
