# Generated by Django 6.1.2 on 2026-10-08 23:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.fournisseur'),
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.magasin'),
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYEE', 'Envoyée au fournisseur'), ('RECUE_PARTIELLEMENT', 'Reçue partiellement'), ('RECUE', 'Reçue'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=30),
        ),
        migrations.AlterField(
            model_name='lignecommandefournisseur',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.produits'),
        ),
        migrations.AlterField(
            model_name='produits',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.categorie'),
        ),
        migrations.AlterField(
            model_name='produits',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='produits',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='produits',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commande_client',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.produits')),
            ],
            options={
                'db_table': 'ligne_commande_client',
            },
        ),
    ]
