# Generated by Django 6.1.2 on 2026-10-09 08:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_clients_et_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée (réception, retour)'), ('SORTIE', 'Sortie (vente, casse, perte)'), ('AJUSTEMENT', 'Ajustement (inventaire)')], max_length=12)),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantite_avant', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantite_apres', models.DecimalField(decimal_places=3, max_digits=12)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mouvement_stock',
                'ordering': ['-date_mouvement', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('seuil_alerte', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text="Une alerte s'affiche quand la quantité est inférieure ou égale à ce seuil.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'db_table': 'stock',
                'ordering': ['produit__nom', 'magasin__nom'],
            },
        ),
        migrations.AddField(
            model_name='magasin',
            name='vente_en_ligne',
            field=models.BooleanField(default=False, help_text='Cochez pour le magasin dont le stock sert aux commandes du site (un seul possible).'),
        ),
        migrations.AddConstraint(
            model_name='magasin',
            constraint=models.UniqueConstraint(condition=models.Q(('vente_en_ligne', True)), fields=('vente_en_ligne',), name='un_seul_magasin_vente_en_ligne'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='commande_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='gestion.commande'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='gestion.magasin'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='gestion.produits'),
        ),
        migrations.AddField(
            model_name='stock',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='gestion.magasin'),
        ),
        migrations.AddField(
            model_name='stock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='gestion.produits'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('produit', 'magasin'), name='un_stock_par_produit_et_magasin'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gte', 0)), name='stock_jamais_negatif'),
        ),
    ]
